---
# TODO:
  # Spotify
  # MEGA
  # Virtualbox
  # Vagrant
  # Homestead
  # Laravel

- name: Setup
  become: fabio
  hosts: all
  vars:
    dotfiles_dir: "{{ ansible_env.HOME }}/dev/dotfiles"
    fonts_dir: "{{ ansible_env.HOME }}/.local/share/fonts/adobe-fonts/source-code-pro"
    go_get:
    - name: sqlfmt
      url: github.com/jackc/sqlfmt/


  tasks:
    - name: Add Emacs PPA for latest version
      become: yes
      apt_repository:
        repo: ppa:kelleyk/emacs

    - name: Install apt packages
      become: yes
      apt:
        pkg:
          - docker
          - emacs26
          - git
          - global
          - golang-go
          - npm
          - python3
          - python3-pip
          - ruby
          - vagrant
          - virtualbox

    - name: Install tern
      become: yes
      npm:
        name: tern
        global: yes

    - name: Install intelephense
      become: yes
      npm:
        name: intelephense
        global: yes

    - name: Clone Source Code Pro fonts
      git:
        repo: https://github.com/adobe-fonts/source-code-pro
        dest: "{{ fonts_dir }}"
        depth: 1

    - name: Install Source Code Pro fonts
      command: fc-cache -f -v {{ fonts_dir }}

    - name: Install virtualenvwrapper
      pip:
        name:
          - virtualenvwrapper
        executable: pip3

    - name: Git clone pyenv repository
      git:
        repo: https://github.com/pyenv/pyenv.git
        dest: "{{ ansible_env.HOME }}/.pyenv"

    - name: Git clone dotfiles repository
      git:
        repo: https://github.com/fabiohsmachado/dotfiles.git
        dest: "{{ dotfiles_dir }}"

    - name: Link dotfiles files to home directory
      file:
        src: "{{ dotfiles_dir }}/{{ item }}"
        dest: "{{ ansible_env.HOME }}/{{ item }}"
        state: link
      with_items:
        - .bashrc_append.sh
        - .bash_profile_append.sh
        - .spacemacs

    - name: Source append files in original dotfiles
      lineinfile:
        path: "{{ ansible_env.HOME }}/{{ item }}"
        line: source {{ansible_env.HOME }}/{{ item }}_append.sh
        create: yes
      with_items:
        - .bashrc
        - .bash_profile

    - name: Install Spacemacs
      git:
        repo: https://github.com/syl20bnr/spacemacs
        dest: "{{ ansible_env.HOME }}/.emacs.d"
        version: develop
...
